### ISSUE TITLE
Can transform style be removed when drag is not in progress?

### ISSUE THREAD

**Issue by spicykoala** [react-grid-layout/react-draggable#188]
Right now the element wrapped with <Draggable> has the value "transform: translate(0px, 0px)" as the default transform value. There is a bug in the w3c spec that shows itself in Chrome when trying to deal with a position: fixed element inside an element that has a transform on it. Because of this I was wondering if there would be a way for me to have the value as "transform: none;" while not in a dragging state.

Thanks for an awesome package!

**Comment by STRML** [comment]
Try setting the following CSS:

``` css
.react-draggable:not(.react-draggable-dragged) {
  transform: none !important;
}
```
