### ISSUE TITLE
touch-action: none prevents scrolling in mobile Chrome when not on drag handle

### ISSUE THREAD

**Issue by DomBlack** [react-grid-layout/react-draggable#227]
If you are using a handle I would only expect react-draggable to prevent touch events on the handle, instead it applies `touch-action: none` to the container, meaning anything inside it (handle or not) cannot receive touch events.

This makes browser scrolling impossible, could you give us a way to disable this behaviour and allow us to manually enable it directly on the drag handle?

**Comment by slnsrn** [comment]
did you find a solution? :)

**Comment by ZechyW** [comment]
As a workaround, you can override `touch-action` on the main container and drag handle by assigning classes like the following:
```css
/* Assign to the main container */
.drag-container{
  touch-action: auto !important;
}

/* Set as the handle class */
.drag-handle {
  touch-action: none;
}
```
This should allow scrolling/pinch-to-zoom/etc. on the container while also allowing the handle to initiate dragging (also see #51).
