### ISSUE TITLE
Dragging over an iframe stops dragging when moving the mouse too fast

### ISSUE THREAD

**Issue by simlmx** [react-grid-layout/react-draggable#582]
I found a solution which I'm sharing here.

I had something that looked like
```jsx
...
return (
  <>
    <iframe></iframe>
    <Draggable>
      <div style={{position: 'absolute'}}></div>
    </Draggable>
  </>
)
```
i.e. a draggable `<div>` on top of an `<iframe>`. When dragging too fast I would lose the drag.

My solution (inspired from [this other post][1]) was this:

```jsx
...
const [isDragging, setIsDragging] = useState(false);

return (
  <>
    {isDragging && (
      <div style={{position: 'absolute', left: 0, right: 0, bottom: 0, top: 0, zIndex: 9999}}</div>
    )}
    <iframe></iframe>
    <Draggable
      onStart={() => setIsDragging(true)}
      onStop={() => setIsDragging(false)}
    >
      <div style={{position: 'absolute'}}></div>
    </Draggable>
  </>
)
```

This makes sure that when we are dragging, we are dragging on top of a big `<div>` instead of the `<iframe>`.

**EDIT** See @Landish's [solution below][2] for something even simpler.

[1]: https://github.com/react-grid-layout/react-draggable/issues/358#issuecomment-500102484
[2]: https://github.com/react-grid-layout/react-draggable/issues/582#issuecomment-1040882678

**Comment by liorocks** [comment]
Amazing solution 👍 

I had the same problem, thanks for sharing, it really helped!

I noticed that react-draggable library adds `.react-draggable-transparent-selection` class to `body` tag while an element is being dragged.

So here is an alternative solution, which is more like CSS approach and does not requires managing `isDragging` state.

```css
.react-draggable-transparent-selection .draggable-iframe-cover {
    display: block;
    z-index: 999999;
}

.draggable-iframe-cover {
    position: absolute;
    display: none;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
}
```

```jsx
<div style={{ position: 'relative' }}>
    <div className="draggable-iframe-cover" />
    <iframe ... />
</div>
```
